# Route Alignment 
___

## 1.1 Route Directness
Using Google Maps and Remix, the roundtrip distance, actual length of the route and the shortest path between the start-end stops were determined. In the northbound direction, the 52 Dundas route starts from Orchard at Pleasant and ends at Watson’s Lane Loop. In the southbound direction, the 52 Dundas route starts from Watson's Lane Loop and ends at Orchard at Pleasant. The roundtrip distance for the 52 Dundas route from northbound to southbound is 10.49 km. The actual length of the route is 5.2 km in both directions (northbound and southbound). The shortest path between the start-end stops is 5.1 km in both directions (northbound and southbound). Generally known, the ratio indicates the route directness. The ratio between the shortest path and the actual route is 0.98 in both directions meaning the route is quite direct.

## 1.2 Service Coverage

According to the census data, and route characteristics from OpenStreetMaps, the population size served by the route is approximately 8245 in both directions. The service coverage area within 400 m of the local bus.

52 Dundas route characteristics: 
```{r, echo=FALSE}

read.csv(file = "data/Route_Characteristics.csv")

```

The information is also summarized below:

Characteristic | Value
- | -
Roundtrip Distance | 10.49 km
Actual Route Length | 5.2 km (inbound) and 5.2 km (outbound)
Shortest Path | 5.1 km
Ratio | 0.98
Population | 8245
Holistic Land Use | Residential
Current Route Operation Cost | $144.9 k/year

## 1.3 Land Use
The northbound and southbound transit routes for 52 Dundas are both mainly comprised of residential land use considering it provides service to an area that is predominantly surrounded by housing infrastructure. Both directions also have few commercial and institutional land uses. This information was extracted with Remix. Alternatively, it can be extracted with census data for Hamilton.
