# Service Frequency
___

The purpose of analyzing the service frequency of an existing transit system is to ensure that the level of service has adequate space to accommodate the maximum number of on-board passengers along the entire route over a given time period. Using Remix, both inbound and outbound timetable data were extracted to analyze both the weekday and weekend frequencies and fleet size. 

To find the service frequency, divide the total operating hours by the number of trips made by the bus which will give you the average time between each buss arrival along the route or at the stop. Keep in mind, frequency and headway are both terms used to describe the time intervals between buses on a particular route or at a specific bus stop. However, they represent this information in slightly different ways. Frequency refers to the number of bus trips or arrivals at a stop within a specific period, often expressed as the number of buses per hour. For example, a bus service with a frequency of 15 minutes means that a bus arrives approximately every 15 minutes at that stop. 

It will be calculated as 1/Time Interval. Headway represents the time interval between the departure or arrival of successive buses. It is the actual time that elapses between one bus leaving or arriving and the next bus following it at a particular stop or along a route.

Headway and frequency can be converted in that:


$$
Frequency = 1/Headway
$$

$$
Headway = 1/Frequency
$$
In other words, Frequency is simply just the inverse of the headway.

$$ Frequency = Headway^{-1} $$

When referring to bus service, a higher frequency or shorter headway generally means better service, providing passengers with more options and shorter waiting times between buses.

## 3.1 Frequency Weekday
The frequency weekday was analyzed for both inbound and outbound directions by graphing the average frequency of the existing service for certain time intervals. Based on the frequency data patterns observed for both inbound and outbound, the level of frequency was consistent along the entire route over different time periods for all stops. This was the case for 52 Dundas considering there was not much change in the level of service along the route. To represent the frequency weekday for this route, the frequency of the inbound stop Orchard at Pleasant, and the outbound stop Watson’s Lane Loop were used as a benchmark. The maximum frequency for both inbound and outbound is 1.67 buses/hr which occurs during both 06:30 – 09:30 AM and 15:00 – 18:00 PM peak hours.

## 3.2 Frequency Weekend
Currently, Route 52 Dundas is not scheduled to run during weekends, hence the frequency for the weekend is zero. It could be that there is not enough demand or ridership during the weekends for the 52 Dundas area. This could be something to reconsider when reconfiguring the route.

## 3.3 Fleet Size
The fleet size for Route 52 is 2 buses for both time periods during the Weekday. As Route 52 does not run-on weekends, there are no fleet sizes reported. The maximum fleet is 2 buses. The buses run every 30 minutes so for the first time period, there is one bus per hour and for the second time period, there is one bus every hour and a half.


```{r, echo=FALSE}

read.csv("data/52_Dundas_Local_Summary.csv")

```
