---
output:
  pdf_document: default
  html_document: default
---
# Conclusion {-}

A simple analysis was completed for 52 Dundas route in an effort to observe the existing system’s infrastructure through changes in operational quality, service quality, and overall connectedness of the transportation grid. From these results, different reconfigurations could be made based on minimizing costs or improving the service within communities in close proximity to the 52 Dundas HSR route. However, it is important to note that there is no perfect, silver-bullet solution for this route or any route for that matter.

The data provided as well as the process of extracting these results have been outlined within this project. File naming, version control with Github, determining the appropriate tools (R Studio and Excel) to use, identifying the infrastructure and then creating a process flow were completed. This project can hopefully be reproduced and repeated with the data and the instructions provided. 

On a personal note, it has been a huge learning experience for me. I have been able to learn many new skills that I did not have at the start of this semester. I came into this course with null knowledge of R and Github and it is amazing what I can now do with the skills I have! Thank you so much Antonio!

