---
title: 'Route Analysis of 52 Dundas'
author: 'Sadia Tasnim'
#date: 'December 2023'
university: 'McMaster University'
faculty: 'Faculty of Engineering'
department: 'Civil Engineering'
subject: 'Reproducible Research with Github and R'
supervisor: 'Antonio Paez'
bdegree: 'B.Eng.' # Bachellor's Degree
knit: bookdown::render_book
site: bookdown::bookdown_site
# Remove the hashtag to specify which version of output you would like.
# Can only choose one at a time.
output:
  thesisdown::thesis_pdf: default 
  keep_tex: true
#  thesisdown::thesis_gitbook: default         
#  thesisdown::thesis_word: default
#  thesisdown::thesis_epub: default

# If you are creating a PDF you'll need to write your preliminary content 
# (e.g., abstract, acknowledgements) below or use code similar to line 25-26 
# for the .RMD files. If you are NOT producing a PDF, delete or silence
# lines 31-56 in this YAML header.

bibliography: bib/thesis.bib
# Download your specific csl file and refer to it in the line below.
csl: csl/apa.csl
lot: true
lof: true
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of 
metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete the section entirely, or silence them (add # before each line). 

If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.

If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the macdown package is
# installed and loaded. This macdown package includes
# the template files for the thesis.
if(!require(remotes))
  install.packages("remotes", repos = "http://cran.rstudio.com")
if(!require(macdown))
  remotes::install_github("paezha/macdown")
library(macdown)
```

<!--
BEGINNING HERE ADD THE DOCUMENTS THAT CONFORM THE MAIN BODY OF THE THESIS
-->

```{r eval=!knitr::is_latex_output(), child=here::here("01-chap1.Rmd")}

```

```{r eval=!knitr::is_latex_output(), child=here::here("02-chap2.Rmd")}

```

```{r eval=!knitr::is_latex_output(), child=here::here("03-chap3.Rmd")}

```

```{r eval=!knitr::is_latex_output(), child=here::here("04-chap4.Rmd")}

```

```{r eval=!knitr::is_latex_output(), child=here::here("05-conclusion.Rmd")}

```

```{r eval=!knitr::is_latex_output(), child=here::here("99-references.Rmd")}

```
