---
title: 'Route Analysis of 52 Dundas'
author: 'Sadia Tasnim'
#date: 'December 2023'
university: 'McMaster University'
faculty: 'Faculty of Engineering'
department: 'Civil Engineering'
subject: 'Reproducible Research with Github and R'
supervisor: 'Antonio Paez'
bdegree: 'B.Eng.' # Bachellor's Degree


knit: bookdown::render_book
site: bookdown::bookdown_site

# Remove the hashtag to specify which version of output you would like.
# Can only choose one at a time.
output:
  thesisdown::thesis_pdf: default 
  keep_tex: true
#  thesisdown::thesis_gitbook: default         
#  thesisdown::thesis_word: default
#  thesisdown::thesis_epub: default

# If you are creating a PDF you'll need to write your preliminary content 
# (e.g., abstract, acknowledgements) below or use code similar to line 25-26 
# for the .RMD files. If you are NOT producing a PDF, delete or silence
# lines 31-56 in this YAML header.

bibliography: bib/thesis.bib
# Download your specific csl file and refer to it in the line below.
csl: csl/apa.csl
lot: true
lof: true
---

# Remove the hashtag to specify which version of output you would like.

Placeholder



<!--chapter:end:index.Rmd-->

---
output:
  pdf_document: default
  html_document: default
---

# Chapter 1: Route Alignment 
___

## 1.1 Route Directness
Using Google Maps and Remix, the roundtrip distance, actual length of the route and the shortest path between the start-end stops were determined. In the northbound direction, the 52 Dundas route starts from Orchard at Pleasant and ends at Watson’s Lane Loop. In the southbound direction, the 52 Dundas route starts from Watson's Lane Loop and ends at Orchard at Pleasant. The roundtrip distance for the 52 Dundas route from northbound to southbound is 10.49 km. The actual length of the route is 5.2 km in both directions (northbound and southbound). The shortest path between the start-end stops is 5.1 km in both directions (northbound and southbound). Generally known, the ratio indicates the route directness. The ratio between the shortest path and the actual route is 0.98 in both directions meaning the route is quite direct.

## 1.2 Service Coverage

According to the census data, and route characteristics from OpenStreetMaps, the population size served by the route is approximately 8245 in both directions. The service coverage area within 400 m of the local bus. Below is a table outline the following characteristics.

Table 1 - 52 Dundas route characteristics
```{r echo - FALSE, results='asis'}
library(knitr)
kable(Route_Characteristics[1:7, ], caption = "52 Dundas route characteristics.")
```



<!--chapter:end:01-chap1.Rmd-->


$$
\sum_{j=1}^n (\delta\theta_j)^2 \leq {{\beta_i^2}\over{\delta_i^2 + \rho_i^2}}
\left[ 2\rho_i^2 + {\delta_i^2\beta_i^2\over{\delta_i^2 + \rho_i^2}} \right] \equiv \omega_i^2
$$

<!--chapter:end:02-chap2.Rmd-->

---
output:
  pdf_document: default
  html_document: default
---
# Conclusion {-}

A simple analysis was completed for 52 Dundas route in an effort to observe the existing system’s infrastructure through changes in operational quality, service quality, and overall connectedness of the transportation grid. From these results, different reconfigurations could be made based on minimizing costs or improving the service within communities in close proximity to the 52 Dundas HSR route. However, it is important to note that there is no perfect, silver-bullet solution for this route or any route for that matter.

The data provided as well as the process of extracting these results have been outlined within this project. File naming, version control with Github, determining the appropriate tools (R Studio and Excel) to use, identifying the infrastructure and then creating a process flow were completed. This project can hopefully be reproduced and repeated with the data and the instructions provided. 

On a personal note, it has been a huge learning experience for me. I have been able to learn many new skills that I did not have at the start of this semester. I came into this course with null knowledge of R and Github and it is amazing what I can now do with the skills I have! Thank you so much Antonio!


<!--chapter:end:03-conclusion.Rmd-->


# References {-}

Placeholder



<!--chapter:end:99-references.Rmd-->

